export const paintingActionTypes = {
	ADD_PAINTING: "ADD_PAINTING",
	INIT_PAINTINGS: "INIT_PAINTINGS"
}

export const youtubeActionTypes = {
	ADD_YOUTUBE: "ADD_YOUTUBE",
	INIT_YOUTUBES: "INIT_YOUTUBES"
}

export const diaryActionTypes = {
	GET_DIARIES_INFO: "GET_DIARIES_INFO",
	ADD_DIARY: "ADD_DIARY",
	GET_DIARIES_BY_CATEGORY: "GET_DIARIES_BY_CATEGORY",
	GET_DIARY: "GET_DIARY",
	GET_DIARIES: "GET_DIARIES",
	SET_DIARY_URL: "SET_DIARY_URL"
}

export const articleActionTypes = {
	QUERY_ARTICLES: 'GET_ARTICLES',
	GET_ARTICLE: 'GET_ARTICLE',
	UPDATE_ARTICLE: 'UPDATE_ARTICLE',
	ADD_ARTICLE: 'ADD_ARITICLE',
	DELETE_ARTICLE: 'DELETE_ARTICLE'
}