export const drawingsActionTypes = {
	ADD_DRAWING: "ADD_DRAWING",
	QUERY_DRAWINGS: "QUERY_DRAWINGS",
	DELETE_DRAWING: "DELETE_DRAWING"
}

export const articleActionTypes = {
	QUERY_ARTICLES: 'GET_ARTICLES',
	GET_ARTICLE: 'GET_ARTICLE',
	UPDATE_ARTICLE: 'UPDATE_ARTICLE',
	ADD_ARTICLE: 'ADD_ARITICLE',
	DELETE_ARTICLE: 'DELETE_ARTICLE',
	QUERY_ARTICLE_CATEGORIES: 'QUERY_ARTICLE_CATEGORIES'
}