export const paintingActionTypes = {
	ADD_PAINTING: "ADD_PAINTING",
	INIT_PAINTINGS: "INIT_PAINTINGS"
}

export const youtubeActionTypes = {
	ADD_YOUTUBE: "ADD_YOUTUBE",
	INIT_YOUTUBES: "INIT_YOUTUBES"
}

export const diaryActionTypes = {
	GET_DIARIES_INFO: "GET_DIARIES_INFO",
	ADD_DIARY: "ADD_DIARY",
	GET_DIARIES_BY_CATEGORY: "GET_DIARIES_BY_CATEGORY",
	GET_DIARY: "GET_DIARY"
}